services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    Starfruit\BuilderBundle\Controller\:
        resource: '../src/Controller'
        public: true
        tags: ['controller.service_arguments']

    Starfruit\BuilderBundle\Command\:
        resource: '../src/Command'
        tags: ['console.command']

    Starfruit\BuilderBundle\Extension\:
        resource: '../src/Extension/*'
        public: true

    Starfruit\BuilderBundle\LinkGenerator\:
        resource: '../src/LinkGenerator/*'
        public: true

    Starfruit\BuilderBundle\Model\:
        resource: '../src/Model/*'

    Starfruit\BuilderBundle\Tool\:
        resource: '../src/Tool/*'

    Starfruit\BuilderBundle\Service\:
        resource: '../src/Service/*'

    Starfruit\BuilderBundle\Config\:
        resource: '../src/Config/*'

    Starfruit\BuilderBundle\Validator\:
        resource: '../src/Validator/*'

    Starfruit\BuilderBundle\Seo\:
        resource: '../src/Seo/*'

    Starfruit\BuilderBundle\Sitemap\:
        resource: '../src/Sitemap/*'

    # ---------------------------------------------------------
    # Event Listener
    # ---------------------------------------------------------
    Starfruit\BuilderBundle\EventListener\Asset\AdminImagePreviewListener:
        tags:
            - { name: kernel.event_listener, event: pimcore.admin.resolve.elementAdminStyle, method: onResolveElementAdminStyle }

    Starfruit\BuilderBundle\EventListener\Object\SlugListener:
        tags:
            - { name: kernel.event_listener, event: pimcore.dataobject.preUpdate, method: preUpdate }
    Starfruit\BuilderBundle\EventListener\Document\StoreAddCodeListener:
        tags:
            - { name: kernel.event_listener, event: pimcore.document.postUpdate, method: postUpdate }

    Starfruit\BuilderBundle\EventListener\Sitemap\RegenerateListener:
        tags:
            - { name: kernel.event_listener, event: pimcore.dataobject.postUpdate, method: postObjectUpdate }
            - { name: kernel.event_listener, event: pimcore.dataobject.postDelete, method: postObjectDelete }
            - { name: kernel.event_listener, event: pimcore.document.postUpdate, method: postDocumentUpdate }
            - { name: kernel.event_listener, event: pimcore.document.postDelete, method: postDocumentDelete }

    Starfruit\BuilderBundle\EventListener\ControllerListener:
        tags:
            - { name: kernel.event_listener, event: kernel.controller }

    Starfruit\BuilderBundle\EventListener\RenderAddCodeListener:
        public: true
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: -108 }

    Starfruit\BuilderBundle\EventListener\Security\ResponseListener:
        public: true
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: -113 }

    Starfruit\BuilderBundle\EventListener\Admin\StyleListener:
        tags:
            - { name: kernel.event_listener, event: pimcore.bundle_manager.paths.css, method: addCSSFiles }
            - { name: kernel.event_listener, event: pimcore.bundle_manager.paths.js, method: addJSFiles }
