framework:
    cache:
        pools:
            pimcore.cache.pool:
                public: true
                default_lifetime: 31536000  # 1 year
                adapter: cache.adapter.redis_tag_aware
                provider: '%env(string:BUILDER_REDIS_DNS_PROVIDER)%'
