pimcore:
    general:
       timezone: Asia/Ho_Chi_Minh

    chromium:
        uri: 'ws://chrome:3000/'

    gotenberg:
        base_url: 'http://gotenberg:3000'

    config_location:
        image_thumbnails:
            write_target:
                type: 'symfony-config'
        video_thumbnails:
            write_target:
                type: 'symfony-config'
        document_types:
            write_target:
                type: 'symfony-config'
        predefined_properties:
            write_target:
                type: 'symfony-config'
        predefined_asset_metadata:
            write_target:
                type: 'symfony-config'
        perspectives:
            write_target:
                type: 'symfony-config'
        custom_views:
            write_target:
                type: 'symfony-config'
        object_custom_layouts:
            write_target:
                type: 'symfony-config'
        system_settings:
            write_target:
                type: 'symfony-config'
            read_target:
                type: 'symfony-config'

pimcore_admin:
    admin_csp_header:
        enabled: true
        exclude_paths:
            - '@^/admin/external_opcache@'

    config_location:
        admin_system_settings:
            write_target:
                type: 'symfony-config'
            read_target:
                type: 'symfony-config'

# pimcore_static_routes:
#     config_location:
#         staticroutes:
#             write_target:
#                 type: 'symfony-config'

# pimcore_custom_reports:
#     config_location:
#         custom_reports:
#             write_target:
#                 type: 'symfony-config'