# install package league/flysystem-aws-s3-v3
services:
    assets_s3:
        class: 'Aws\S3\S3Client'
        arguments:
            -   endpoint: 'https://%env(string:S3_ENDPOINT)%'
                region: '%env(string:S3_REGION)%'
                version: 'latest'
                credentials:
                    key: '%env(string:S3_KEY)%'
                    secret: '%env(string:S3_SECRET)%'
flysystem:
    storages:
        pimcore.asset.storage:
            adapter: 'aws'
            visibility: public
            options:
                client: 'assets_s3'
                bucket: '%env(string:S3_BUCKET)%'
                prefix: assets

        pimcore.thumbnail.storage:
            adapter: 'aws'
            visibility: public
            options:
                client: 'assets_s3'
                bucket: '%env(string:S3_BUCKET)%'
                prefix: thumbnail

        pimcore.asset_cache.storage:
            adapter: 'aws'
            visibility: public
            options:
                client: 'assets_s3'
                bucket: '%env(string:S3_BUCKET)%'
                prefix: asset_cache

        pimcore.asset.storage.source:
            adapter: 'local'
            visibility: public
            options:
                directory: '%kernel.project_dir%/public/var/assets'

        pimcore.asset.storage.target:
            adapter: 'aws'
            visibility: public
            options:
                client: 'assets_s3'
                bucket: '%env(string:S3_BUCKET)%'
                prefix: assets

        pimcore.thumbnail.storage.source:
            adapter: 'local'
            visibility: public
            options:
                directory: '%kernel.project_dir%/public/var/tmp/thumbnails'

        pimcore.thumbnail.storage.target:
            adapter: 'aws'
            visibility: public
            options:
                client: 'assets_s3'
                bucket: '%env(string:S3_BUCKET)%'
                prefix: thumbnail

        pimcore.asset_cache.storage.source:
            adapter: 'local'
            visibility: public
            options:
                directory: '%kernel.project_dir%/public/var/tmp/asset_cache'

        pimcore.asset_cache.storage.target:
            adapter: 'aws'
            visibility: public
            options:
                client: 'assets_s3'
                bucket: '%env(string:S3_BUCKET)%'
                prefix: asset_cache