pimcore_seo:
    sitemaps:
        generators:
            default:
                enabled: true
                priority: 50
                generator_id: Starfruit\BuilderBundle\Sitemaps\Generator

            # Pimcore ships a default document tree generator which is enabled by default
            # but you can easily disable it here.
            pimcore_documents:
                enabled: false
    redirects:
        auto_create_redirects: true
