# starfruit_builder_api:
#     resource: "@StarfruitBuilderBundle/src/Controller/API/"
#     type: annotation

starfruit_builder_default:
    resource: "@StarfruitBuilderBundle/src/Controller/*"
    type: annotation
