# starfruit_builder:
#     link_generate_objects:
#         classid:
#             class_name: ClassName
#             field_create_slug: name
#             field_for_slug: slug
#             update_while_empty: true
#             seo_fields:
#                 title:
#                 description:
#                 image:
#     seo:
#         image_thumbnail: 'seo_thumbnail'
